[mypy]
# Obliga a poner tipos en las funciones
disallow_untyped_defs = True
# Avisa si una librería no tiene tipos
ignore_missing_imports = False
# No permitas valores 'None' inesperados
strict_optional = True
[mypy-behave.*]
ignore_missing_imports = True